### ISSUE TITLE
concat_csv: FileNotFoundError

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/vertebral-labeling-validation#4]
I'm getting this error:

```bash
python concat_csv.py -p results_pred_20201022/results/data/derivatives/labels/
Traceback (most recent call last):
  File "concat_csv.py", line 30, in <module>
    main()
  File "concat_csv.py", line 26, in main
    concat_csv(args.path)
  File "concat_csv.py", line 16, in concat_csv
    df_results = pd.concat([pd.read_csv(os.path.join(f,"anat","result.csv"), index_col="file") for f in t ])
  File "concat_csv.py", line 16, in <listcomp>
    df_results = pd.concat([pd.read_csv(os.path.join(f,"anat","result.csv"), index_col="file") for f in t ])
  File "/Users/julien/code/vertebral-labeling-validation/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/julien/code/vertebral-labeling-validation/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/Users/julien/code/vertebral-labeling-validation/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 946, in __init__
    self._make_engine(self.engine)
  File "/Users/julien/code/vertebral-labeling-validation/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 1178, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/julien/code/vertebral-labeling-validation/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 2008, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: 'sub-tokyo750w02/anat/result.csv'
```

Versions:
- vertebral-labeling-validation: 76dcf0d
- SCT: 2cf7545ba5f9f8756743b09fc68fe2b614c07111
- spine-generic data: 47a3bdcddeef8da0e5f19d15e9b1464bccf67b12

**Comment by jcohenadad** [comment]
Additional info:
I realize that the file `result.csv` was only created in the first subject:
~~~
julien-macbook:~/code/vertebral-labeling-validation/results_pred_20201022/results/data/derivatives/labels $ ll
total 0
drwxr-xr-x  8 julien  staff  256 22 Oct 13:58 .
drwxr-xr-x  3 julien  staff   96 22 Oct 13:58 ..
drwxr-xr-x  3 julien  staff   96 22 Oct 13:58 sub-amu02
drwxr-xr-x  3 julien  staff   96 22 Oct 13:58 sub-tokyo750w02
drwxr-xr-x  3 julien  staff   96 22 Oct 13:58 sub-tokyoIngenia02
drwxr-xr-x  3 julien  staff   96 22 Oct 13:58 sub-unf01
drwxr-xr-x  3 julien  staff   96 22 Oct 13:58 sub-unf02
drwxr-xr-x  3 julien  staff   96 22 Oct 13:58 sub-vallHebron02
julien-macbook:~/code/vertebral-labeling-validation/results_pred_20201022/results/data/derivatives/labels $ find . -name result.csv
./sub-amu02/anat/result.csv
~~~

So, something probably went wrong in the generation of those files for the other subjects.

**Comment by jcohenadad** [comment]
Here is the culprit: the missing files are caused by errors during the processing. Those subjects were not processed completely. I'm getting this error:
```bash
ValueError: Input and reference image don't have the same number of labels! 10 vs 9
```
Full log: [log.zip](https://github.com/sct-pipeline/vertebral-labeling-validation/files/5425625/log.zip)

**Comment by lrouhier** [comment]
I guess this is linked in part to #1 I will check that out.

**Comment by jcohenadad** [comment]
@lrouhier out of curiosity: have you tested the pipeline yourself? if so, did it work? if so, why did it work in your case and not mine?

**Comment by lrouhier** [comment]
Yes I have, And the main reason is that I have only tested on the first subject locally, I guess it was just lucky that it works on this one. I will look into it and do a full test.

**Comment by jcohenadad** [comment]
> Yes I have, And the main reason is that I have only tested on the first subject locally, I guess it was just lucky that it works on this one. I will look into it and do a full test.

here's my config file, which includes the subjects i used: 
```yaml
path_data: /Users/julien/code/spine-generic/data-multi-subject
path_output: /Users/julien/code/vertebral-labeling-validation/results_20201022
script: /Users/julien/code/vertebral-labeling-validation/prepare_seg_and_gt.sh
jobs: -1
batch_log: sct_run_batch_log.txt
continue_on_error: 1
subject_prefix: sub-
include_list: ['sub-unf01', 'sub-unf02', 'sub-amu02', 'sub-vallHebron02', 'sub-tokyoIngenia02', 'sub-tokyo750w02']
zip: true
```

**Comment by joshuacwnewton** [comment]
I've reworked the pipeline to be a little simpler -- now instead of having a two step process (1. Python code contained in shell script that outputs a results.csv for each subject, then 2. concat_csv.py to merge the per-subject results) all of the processing is done in a single Python script (.nii.gz -> `analyze_predictions.py` -> append to single results.csv), which I hope will make things simpler/less error-prone.

Since this issue is out of date, I'm closing for clean-up purposes.
